FROM python:3.11-slim

WORKDIR /scraping-service

ENV PATH="/scraping-service/.venv/bin:$PATH"

# Install dependencies with uv
RUN pip install uv

COPY ./pyproject.toml /scraping-service

RUN uv sync

# Install chromedriver
RUN apt-get update && apt-get install wget unzip -y && \
    wget https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/linux64/chromedriver-linux64.zip -O /tmp/chromedriver.zip && \
    unzip /tmp/chromedriver.zip -d /tmp/chromedriver && \
    mv /tmp/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/

# Install chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get install -y libasound2 \ 
            libatk-bridge2.0-0 \ 
            libatk1.0-0 \ 
            libatspi2.0-0 \ 
            libcups2 \ 
            libdbus-1-3 \
            libgbm1 \
            libgtk-4-1 \
            libnspr4 \
            libnss3 \
            libvulkan1  \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3  \
            libxkbcommon0 \
            libxrandr2  \
            xdg-utils && \
    apt install -y ./google-chrome*.deb

COPY . /scraping-service

CMD ["fastapi", "run", "main.py"]