[project]
name = "scraping-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "lxml>=5.4.0",
    "requests>=2.32.3",
    "selenium>=4.33.0",
]
